[build]
    publish = ".next"
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[plugins]]
    package = "netlify-plugin-git-lfs-include"

[plugin.inputs]
    include = ["/public/images/profile.jpg"]